param:
  INITIAL_MODE: 16
  WPNAV_SPEED: 500
  ARMING_CHECK: 2114
  RC5_OPTION: 153
  RC6_OPTION: 0 # arm
  RC7_OPTION: 4   # rtl
  RC8_OPTION: 18
  FLTMODE_CH: 6
  FLTMODE1: 16
  FLTMODE2: 16
  FLTMODE3: 0
  FLTMODE4: 0
  FLTMODE5: 3
  FLTMODE6: 3
  GUID_OPTIONS: 1