param:
  PLND_ENABLED: 1
  PLND_TYPE: 1
  PLND_OPTIONS: 1
  # 只在仿真中使用
  SIM_SONAR_SCALE: 10
  RNGFND1_TYPE: 1
  RNGFND1_SCALING: 10
  RNGFND1_PIN: 0
  RNGFND1_MAX: 50
  RNGFND1_MIN: 0

# rc:
#   6: 1500
#   7: 1300
#   8: 1500