param:
  PLND_ENABLED: 0
  PLND_TYPE: 1
  PLND_OPTIONS: 1
  INITIAL_MODE: 16
  WPNAV_SPEED: 500
  ARMING_CHECK: 2118
  RC5_OPTION: 153
  RC6_OPTION: 0 # arm
  RC7_OPTION: 4   # rtl
  RC8_OPTION: 18
  FLTMODE_CH: 6
  FLTMODE1: 16
  FLTMODE2: 16
  FLTMODE3: 0
  FLTMODE4: 0
  FLTMODE5: 3
  FLTMODE6: 3
  GUID_OPTIONS: 1
  # 只在仿真中使用
  # SIM_SONAR_SCALE: 10
  # RNGFND1_TYPE: 1
  # RNGFND1_SCALING: 10
  # RNGFND1_PIN: 0
  # RNGFND1_MAX: 50
  # RNGFND1_MIN: 0

# rc:
#   6: 1500
#   7: 1300
#   8: 1500